#1 - what is the total revenue generated by male vs female customer?

SELECT gender,SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;

# 2- which customer used discount but still spent more than the average purchase amount?

SELECT customer_id,purchase_amount
FROM customers
WHERE discount_applied = 'yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customers
  )
LIMIT 10;


#3- which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating)::numeric, 2) AS "average product rating"
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


#4 - compare the average purchase amount between standard and express shipping.

SELECT shipping_type,ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase_amount
FROM customers
WHERE shipping_type IN ('standard', 'express')
GROUP BY shipping_type;


#5 - do subscribed customer spend more? compare average spend and total revenue between subscribers and non- subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS "total_customers",
    ROUND(AVG(purchase_amount)::numeric, 2) AS "avg_spend",
    ROUND(SUM(purchase_amount)::numeric, 2) AS "total_revenue"
FROM customers
GROUP BY subscription_status
ORDER BY 
    SUM(purchase_amount) DESC,
    AVG(purchase_amount) DESC;

#6 - which product have the highest percentage of purchase with discount applied?

SELECT  item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


#7 - segment cutomers into new, returning, and loyal based on their total number of previous purchase, and show the count of each segment.

WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customers
)

SELECT 
    customer_segment,
    COUNT(*) AS "number_of_customers"
FROM customer_type
GROUP BY customer_segment;

#8 - what are the top 3 most purchased products within each category.

SELECT 
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM customers
    GROUP BY category, item_purchased
) ranked_products
WHERE rank_in_category <= 3
ORDER BY category, purchase_count DESC;




#9 - are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT  subscription_status, COUNT(DISTINCT customer_id) AS "repeat_buyers"
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

#10 - what is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
